# Streamlit Secrets for AI YouTube Control Center

[general]
email = "your_email@example.com"

[api_keys]
youtube_api_key = "YOUR_YOUTUBE_API_KEY"
google_api_key = "YOUR_GOOGLE_API_KEY"

[oauth]
client_id = "YOUR_CLIENT_ID"
client_secret = "YOUR_CLIENT_SECRET"
redirect_uri = "https://your-app.streamlit.app"
